"""modelagem db

Revision ID: 3ceb7311ecd0
Revises: 
Create Date: 2025-07-02 20:55:46.054232

"""
from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ceb7311ecd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dados_abertos', sa.Integer(), nullable=False),
    sa.Column('sigla', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('nome_completo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('uri_logo', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id_legislativo', sa.Integer(), nullable=True),
    sa.Column('situacao', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('total_membros', sa.Integer(), nullable=True),
    sa.Column('total_posse_legislatura', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_partido_id_dados_abertos'), 'partido', ['id_dados_abertos'], unique=True)
    op.create_table('proposicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dados_abertos', sa.Integer(), nullable=False),
    sa.Column('sigla_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('ementa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_apresentacao', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('url_inteiro_teor', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposicao_id_dados_abertos'), 'proposicao', ['id_dados_abertos'], unique=True)
    op.create_table('sessaovotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dados_abertos', sa.Integer(), nullable=False),
    sa.Column('data_hora_registro', sa.DateTime(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('sigla_orgao', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('aprovacao', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('descrico_ultima_abertura_votacao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessaovotacao_id_dados_abertos'), 'sessaovotacao', ['id_dados_abertos'], unique=True)
    op.create_table('deputado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dados_abertos', sa.Integer(), nullable=False),
    sa.Column('nome_civil', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nome_eleitoral', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sigla_partido', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sigla_uf', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=True),
    sa.Column('id_legislativo', sa.Integer(), nullable=True),
    sa.Column('url_foto', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.ForeignKeyConstraint(['id_partido'], ['partido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deputado_id_dados_abertos'), 'deputado', ['id_dados_abertos'], unique=True)
    op.create_table('votacaoproposicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proposicao', sa.Integer(), nullable=False),
    sa.Column('id_votacao', sa.Integer(), nullable=False),
    sa.Column('tipo_relacao', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_proposicao'], ['proposicao.id'], ),
    sa.ForeignKeyConstraint(['id_votacao'], ['sessaovotacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votacaoproposicao_id_proposicao'), 'votacaoproposicao', ['id_proposicao'], unique=False)
    op.create_index(op.f('ix_votacaoproposicao_id_votacao'), 'votacaoproposicao', ['id_votacao'], unique=False)
    op.create_table('despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dados_abertos', sa.Integer(), nullable=True),
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('tipo_despesa', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('valor_liquido', sa.Float(), nullable=False),
    sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('url_documento', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('nome_fornecedor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_deputado'], ['deputado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesa_id_dados_abertos'), 'despesa', ['id_dados_abertos'], unique=True)
    op.create_index(op.f('ix_despesa_id_deputado'), 'despesa', ['id_deputado'], unique=False)
    op.create_table('gabinete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('predio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sala', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('andar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_deputado'], ['deputado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gabinete_id_deputado'), 'gabinete', ['id_deputado'], unique=True)
    op.create_table('votoindividual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dados_abertos', sa.Integer(), nullable=True),
    sa.Column('id_votacao', sa.Integer(), nullable=False),
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('id_proposicao', sa.Integer(), nullable=False),
    sa.Column('tipo_voto', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('data_hora_registro', sa.DateTime(), nullable=True),
    sa.Column('sigla_partido_deputado', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('uri_deputado', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_deputado'], ['deputado.id'], ),
    sa.ForeignKeyConstraint(['id_proposicao'], ['proposicao.id'], ),
    sa.ForeignKeyConstraint(['id_votacao'], ['sessaovotacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votoindividual_id_dados_abertos'), 'votoindividual', ['id_dados_abertos'], unique=True)
    op.create_index(op.f('ix_votoindividual_id_deputado'), 'votoindividual', ['id_deputado'], unique=False)
    op.create_index(op.f('ix_votoindividual_id_proposicao'), 'votoindividual', ['id_proposicao'], unique=False)
    op.create_index(op.f('ix_votoindividual_id_votacao'), 'votoindividual', ['id_votacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votoindividual_id_votacao'), table_name='votoindividual')
    op.drop_index(op.f('ix_votoindividual_id_proposicao'), table_name='votoindividual')
    op.drop_index(op.f('ix_votoindividual_id_deputado'), table_name='votoindividual')
    op.drop_index(op.f('ix_votoindividual_id_dados_abertos'), table_name='votoindividual')
    op.drop_table('votoindividual')
    op.drop_index(op.f('ix_gabinete_id_deputado'), table_name='gabinete')
    op.drop_table('gabinete')
    op.drop_index(op.f('ix_despesa_id_deputado'), table_name='despesa')
    op.drop_index(op.f('ix_despesa_id_dados_abertos'), table_name='despesa')
    op.drop_table('despesa')
    op.drop_index(op.f('ix_votacaoproposicao_id_votacao'), table_name='votacaoproposicao')
    op.drop_index(op.f('ix_votacaoproposicao_id_proposicao'), table_name='votacaoproposicao')
    op.drop_table('votacaoproposicao')
    op.drop_index(op.f('ix_deputado_id_dados_abertos'), table_name='deputado')
    op.drop_table('deputado')
    op.drop_index(op.f('ix_sessaovotacao_id_dados_abertos'), table_name='sessaovotacao')
    op.drop_table('sessaovotacao')
    op.drop_index(op.f('ix_proposicao_id_dados_abertos'), table_name='proposicao')
    op.drop_table('proposicao')
    op.drop_index(op.f('ix_partido_id_dados_abertos'), table_name='partido')
    op.drop_table('partido')
    # ### end Alembic commands ###
