"""modificandoTamVar

Revision ID: 777a080547e9
Revises: 3ceb7311ecd0
Create Date: 2025-07-03 16:48:19.484151

"""
from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777a080547e9'
down_revision: Union[str, None] = '3ceb7311ecd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deputado', 'sigla_partido',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('despesa', 'tipo_despesa',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=300),
               existing_nullable=False)
    op.alter_column('despesa', 'tipo_documento',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=True)
    op.alter_column('partido', 'sigla',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('votoindividual', 'sigla_partido_deputado',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votoindividual', 'sigla_partido_deputado',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('partido', 'sigla',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('despesa', 'tipo_documento',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('despesa', 'tipo_despesa',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('deputado', 'sigla_partido',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
