"""Retirando_ID_DadosAbertos_Despesa

Revision ID: 92764d8bdfc8
Revises: 777a080547e9
Create Date: 2025-07-05 19:34:58.464767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92764d8bdfc8'
down_revision: Union[str, None] = '777a080547e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_despesa_id_dados_abertos'), table_name='despesa')
    op.drop_column('despesa', 'id_dados_abertos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesa', sa.Column('id_dados_abertos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_despesa_id_dados_abertos'), 'despesa', ['id_dados_abertos'], unique=True)
    # ### end Alembic commands ###
