"""mod5

Revision ID: 9292c3d19dd3
Revises: aec808c6d145
Create Date: 2025-07-09 15:21:28.412502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9292c3d19dd3'
down_revision: Union[str, None] = 'aec808c6d145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessaovotacao', 'descricao',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessaovotacao', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
