"""mod4

Revision ID: aec808c6d145
Revises: 00b5f379c95b
Create Date: 2025-07-09 15:17:06.041389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec808c6d145'
down_revision: Union[str, None] = '00b5f379c95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessaovotacao', 'descricao_ultima_abertura_votacao',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessaovotacao', 'descricao_ultima_abertura_votacao',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
