"""mod6

Revision ID: f9f12b70d9a3
Revises: 9292c3d19dd3
Create Date: 2025-07-09 15:38:21.435543

"""
from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f12b70d9a3'
down_revision: Union[str, None] = '9292c3d19dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposicao', 'ementa',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('proposicao', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sessaovotacao', 'sigla_orgao',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.alter_column('sessaovotacao', 'aprovacao',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.alter_column('sessaovotacao', 'uri',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessaovotacao', 'uri',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('sessaovotacao', 'aprovacao',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('sessaovotacao', 'sigla_orgao',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('proposicao', 'status',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('proposicao', 'ementa',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
