"""modificandoVoto

Revision ID: fb1e6aad9410
Revises: f9f12b70d9a3
Create Date: 2025-07-10 10:11:25.002019

"""
from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb1e6aad9410'
down_revision: Union[str, None] = 'f9f12b70d9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votoindividual', sa.Column('uri_sessao_votacao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.alter_column('votoindividual', 'tipo_voto',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('votoindividual', 'data_hora_registro',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_votoindividual_id_dados_abertos'), table_name='votoindividual')
    op.drop_index(op.f('ix_votoindividual_id_proposicao'), table_name='votoindividual')
    op.drop_constraint(op.f('votoindividual_id_proposicao_fkey'), 'votoindividual', type_='foreignkey')
    op.drop_column('votoindividual', 'id_proposicao')
    op.drop_column('votoindividual', 'id_dados_abertos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votoindividual', sa.Column('id_dados_abertos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('votoindividual', sa.Column('id_proposicao', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('votoindividual_id_proposicao_fkey'), 'votoindividual', 'proposicao', ['id_proposicao'], ['id'])
    op.create_index(op.f('ix_votoindividual_id_proposicao'), 'votoindividual', ['id_proposicao'], unique=False)
    op.create_index(op.f('ix_votoindividual_id_dados_abertos'), 'votoindividual', ['id_dados_abertos'], unique=True)
    op.alter_column('votoindividual', 'data_hora_registro',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('votoindividual', 'tipo_voto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('votoindividual', 'uri_sessao_votacao')
    # ### end Alembic commands ###
