"""modificando

Revision ID: fc46aa1481f3
Revises: 92764d8bdfc8
Create Date: 2025-07-09 13:55:09.323565

"""
from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc46aa1481f3'
down_revision: Union[str, None] = '92764d8bdfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposicao', 'id_dados_abertos',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('sessaovotacao', sa.Column('descricao_ultima_abertura_votacao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.alter_column('sessaovotacao', 'id_dados_abertos',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('sessaovotacao', 'data_hora_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('sessaovotacao', 'descrico_ultima_abertura_votacao')
    op.drop_column('votacaoproposicao', 'tipo_relacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votacaoproposicao', sa.Column('tipo_relacao', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sessaovotacao', sa.Column('descrico_ultima_abertura_votacao', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('sessaovotacao', 'data_hora_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sessaovotacao', 'id_dados_abertos',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('sessaovotacao', 'descricao_ultima_abertura_votacao')
    op.alter_column('proposicao', 'id_dados_abertos',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
